upstream ycrouter_backend {
  server 192.168.0.1:443;
}

upstream ycrouter_luci {
  server 192.168.0.1:8443;
}

server {
  listen      443 ssl;
  listen      [::]:443 ssl;
  listen      443 quic;
  listen      [::]:443 quic;

  server_name ycrouter.ycholocron.com;

  include /etc/nginx/default.d/*.conf;

  location / {
    proxy_pass          https://ycrouter_backend;
    proxy_http_version  1.1;
    proxy_buffering     off;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header    Host            $host;
    proxy_set_header    X-Forwarded-For $remote_addr;
    proxy_set_header    Origin          http://$host;
  }

  location /cgi-bin/luci/ {
    proxy_pass https://ycrouter_luci;
    proxy_http_version  1.1;
    proxy_buffering     off;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header    Host            $host;
    proxy_set_header    X-Forwarded-For $remote_addr;
    proxy_set_header    Origin          http://$host;
  }

  location /ubus/ {
    proxy_pass https://ycrouter_luci;
    proxy_http_version  1.1;
    proxy_buffering     off;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header    Host            $host;
    proxy_set_header    X-Forwarded-For $remote_addr;
    proxy_set_header    Origin          http://$host;
    error_log stderr crit;
  }

  location /luci-static/ {
    proxy_pass https://ycrouter_luci;
    proxy_http_version  1.1;
    proxy_buffering     off;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header    Host            $host;
    proxy_set_header    X-Forwarded-For $remote_addr;
    proxy_set_header    Origin          http://$host;
    error_log stderr crit;
  }
}
